COCO_SUPERCATEGORIES = {
    "person": "person",
    "bicycle": "vehicle",
    "car": "vehicle",
    "motorcycle": "vehicle",
    "airplane": "vehicle",
    "bus": "vehicle",
    "train": "vehicle",
    "truck": "vehicle",
    "boat": "vehicle",
    "traffic light": "outdoor",
    "fire hydrant": "outdoor",
    "stop sign": "outdoor",
    "parking meter": "outdoor",
    "bench": "furniture",
    "bird": "animal",
    "cat": "animal",
    "dog": "animal",
    "horse": "animal",
    "sheep": "animal",
    "cow": "animal",
    "elephant": "animal",
    "bear": "animal",
    "zebra": "animal",
    "giraffe": "animal",
    "backpack": "accessory",
    "umbrella": "accessory",
    "handbag": "accessory",
    "tie": "accessory",
    "suitcase": "accessory",
    "frisbee": "sports",
    "skis": "sports",
    "snowboard": "sports",
    "sports ball": "sports",
    "kite": "sports",
    "baseball bat": "sports",
    "baseball glove": "sports",
    "skateboard": "sports",
    "surfboard": "sports",
    "tennis racket": "sports",
    "bottle": "kitchen",
    "wine glass": "kitchen",
    "cup": "kitchen",
    "fork": "kitchen",
    "knife": "kitchen",
    "spoon": "kitchen",
    "bowl": "kitchen",
    "banana": "food",
    "apple": "food",
    "sandwich": "food",
    "orange": "food",
    "broccoli": "food",
    "carrot": "food",
    "hot dog": "food",
    "pizza": "food",
    "donut": "food",
    "cake": "food",
    "chair": "furniture",
    "couch": "furniture",
    "potted plant": "indoor",
    "bed": "furniture",
    "dining table": "furniture",
    "toilet": "indoor",
    "tv": "electronic",
    "laptop": "electronic",
    "mouse": "electronic",
    "remote": "electronic",
    "keyboard": "electronic",
    "cell phone": "electronic",
    "microwave": "appliance",
    "oven": "appliance",
    "toaster": "appliance",
    "sink": "appliance",
    "refrigerator": "appliance",
    "book": "indoor",
    "clock": "indoor",
    "vase": "indoor",
    "scissors": "indoor",
    "teddy bear": "toy",
    "hair drier": "appliance",
    "toothbrush": "appliance"
}
